export const data = [
  {
    id: 1,
    title: 'Melting Cheesey',
    calo: '44 calories',
    img: require('../../image/image3.png'),
    price: '9.47',
  },
  {
    id: 2,
    title: 'Melting Cheesey',
    calo: '44 calories',
    img: require('../../image/image2.png'),
    price: '12.55',
  },
  {
    id: 3,
    title: 'Melting Cheesey',
    calo: '44 calories',
    img: require('../../image/image3.png'),
    price: '9.47',
  },
  {
    id: 4,
    title: 'Melting Cheesey',
    calo: '44 calories',
    img: require('../../image/image2.png'),
    price: '12.55',
  },
  {
    id: 5,
    title: 'Melting Cheesey',
    calo: '44 calories',
    img: require('../../image/image3.png'),
    price: '9.47',
  },
  {
    id: 6,
    title: 'Melting Cheesey',
    calo: '44 calories',
    img: require('../../image/image2.png'),
    price: '12.55',
  },
];
export const dataItalia = [
  {
    id: 7,
    title: 'Italian food',
    calo: '44 calories',
    img: require('../../image/image3.png'),
    price: '9.47',
  },
  {
    id: 8,
    title: 'Italian food',
    calo: '44 calories',
    img: require('../../image/image2.png'),
    price: '12.55',
  },
  {
    id: 9,
    title: 'Italian food',
    calo: '44 calories',
    img: require('../../image/image3.png'),
    price: '9.47',
  },
  {
    id: 10,
    title: 'Italian food',
    calo: '44 calories',
    img: require('../../image/image2.png'),
    price: '12.55',
  },
  {
    id: 11,
    title: 'Italian food',
    calo: '44 calories',
    img: require('../../image/image3.png'),
    price: '9.47',
  },
  {
    id: 12,
    title: 'Italian food',
    calo: '44 calories',
    img: require('../../image/image2.png'),
    price: '12.55',
  },
];
export const dataJapan = [
  {
    id: 13,
    title: 'Japanese food',
    calo: '44 calories',
    img: require('../../image/japan1.png'),
    price: '9.47',
  },
  {
    id: 14,
    title: 'Japanese food',
    calo: '44 calories',
    img: require('../../image/japan2.png'),
    price: '12.55',
  },
  {
    id: 15,
    title: 'Japanese food',
    calo: '44 calories',
    img: require('../../image/japan1.png'),
    price: '9.47',
  },
  {
    id: 16,
    title: 'Japanese food',
    calo: '44 calories',
    img: require('../../image/japan2.png'),
    price: '12.55',
  },
  {
    id: 17,
    title: 'Japanese food',
    calo: '44 calories',
    img: require('../../image/japan1.png'),
    price: '9.47',
  },
  {
    id: 18,
    title: 'Japanese food',
    calo: '44 calories',
    img: require('../../image/japan2.png'),
    price: '12.55',
  },
];
export const dataSea = [
  {
    id: 19,
    title: 'Seafood',
    calo: '44 calories',
    img: require('../../image/sea1.png'),
    price: '9.47',
  },
  {
    id: 20,
    title: 'Seafood',
    calo: '44 calories',
    img: require('../../image/sea2.png'),
    price: '12.55',
  },
  {
    id: 21,
    title: 'Seafood',
    calo: '44 calories',
    img: require('../../image/sea1.png'),
    price: '9.47',
  },
  {
    id: 22,
    title: 'Seafood',
    calo: '44 calories',
    img: require('../../image/sea2.png'),
    price: '12.55',
  },
  {
    id: 23,
    title: 'Seafood',
    calo: '44 calories',
    img: require('../../image/sea1.png'),
    price: '9.47',
  },
  {
    id: 24,
    title: 'Seafood',
    calo: '44 calories',
    img: require('../../image/sea2.png'),
    price: '12.55',
  },
];
